<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "soundcloud_helper"
 *
 * Auto generated by Extension Builder 2017-05-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'soundcloud',
    'description' => 'An Extension to embed Soundcloud Iframe without users having to use the HTML Content Element',
    'category' => 'plugin',
    'author' => 'Tim Jonas Pflaum',
    'author_email' => 'tim-jonas.pflaum@liebenzell.org',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
